package std

import "fmt"

func Concat(left, right interface{}) string {
	return interfaceToString(left) + interfaceToString(right)
}

func interfaceToString(i interface{}) string {
	switch i := i.(type) {
	case int:
		return fmt.Sprintf("%d", i)

	// Not generated by parser.
	case float32:
		panic(`Float32 should not be here.`)

	case float64:
		return fmt.Sprintf("%g", i)

	case string:
		return i

	case fmt.Formatter:
		return i.(fmt.Stringer).String()
	}
	return ""
}
