package std

import "fmt"

// Concat joins two values, interfaces, to one string.
// Represents PHP's "." concat operator.
func Concat(left, right interface{}) string {
	return interfaceToString(left) + interfaceToString(right)
}

func interfaceToString(i interface{}) string {
	switch i := i.(type) {
	case int:
		return fmt.Sprintf("%d", i)

	// Not generated by parser.
	case float32:
		panic(`Float32 should not be here.`)

	case float64:
		return fmt.Sprintf("%g", i)

	case string:
		return i

	case fmt.Formatter:
		return i.(fmt.Stringer).String()
	}
	return ""
}

// StrDec behaves the same way
// as PHP string--.
// TODO: Implement this.
func StrDec(s string) string {
	return s
}

// StrInc behaves the same way
// as PHP string++.
// TODO: Implement this.
func StrInc(s string) string {
	return s
}
